# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://mateusblopes.github.io/
baseurl: https://mateusblopes.github.io/
title: Mateus Bruno T. Lopes
author: Mateus Bruno T. Lopes
description: Mateus Bruno T. Lopes - Consultor de Data Science | Scrum Master | Analytics | Power BI
avatar: profile.png
email: mateus.redes@gmail.com
github: mateusblopes # username
twitter: mateusblopes
linkedin: mateusblopes
#Comment out if you don't want disqus 
#disqus: mateusblopes
google_analytics: UA-86360610-1

# needed for travis-ci build
exclude: [vendor]
